kind: ReplicationController
apiVersion: v1
metadata:
  name: [ZOO_PREF]-kafka-manager-controller-v1
spec:
  replicas: 1
  selector:
    component: [ZOO_PREF]-kafka-manager
    version: v1
  template:
    metadata:
      labels:
        component: [ZOO_PREF]-kafka-manager
        version: v1
    spec:
      nodeSelector:
        # run the label command to prepare
        # kubectl label node <SOME NODE> brokerNode=kafka-[ENV_NAME]-1
        brokerNode: kafka-[ENV_NAME]-1
      containers:
        - name: [ZOO_PREF]-kafka-manager
          image: navicore/kafka-manager:1.3.3.4
          env:
            - name: ZK_HOSTS
              value: "[ZOO_PREF]1:2181,[ZOO_PREF]2:2181,[ZOO_PREF]3:2181"
            - name: ZK_VERSION
              value: "3.4.9"
          ports:
            - containerPort: 9000
          livenessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 5

