apiVersion: v1
kind: Service
metadata:
  name: [ZOO_PREF]1
  labels:
    app: [ZOO_PREF]keeper-1
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    app: [ZOO_PREF]keeper-1
---
apiVersion: v1
kind: Service
metadata:
  name: [ZOO_PREF]2
  labels:
    app: [ZOO_PREF]keeper-2
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    app: [ZOO_PREF]keeper-2
---
apiVersion: v1
kind: Service
metadata:
  name: [ZOO_PREF]3
  labels:
    app: [ZOO_PREF]keeper-3
spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP
  - name: follower
    port: 2888
    protocol: TCP
  - name: leader
    port: 3888
    protocol: TCP
  selector:
    app: [ZOO_PREF]keeper-3

