---
apiVersion: v1
kind: Service
metadata:
  name: kafka-[ENV_NAME]-[BROKER_ID]
  labels:
    name: kafka-[ENV_NAME]-[BROKER_ID]
    service: kafka-[ENV_NAME]
    broker_id: "[BROKER_ID]"
spec:
  ports:
    - name: broker
      port: 9092
    - name: jmx
      port: 9999
  selector:
    name: kafka-[ENV_NAME]-[BROKER_ID]
    broker_id: "[BROKER_ID]"

