---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kafka-[ENV_NAME]-[BROKER_ID]
  labels:
    name: kafka-[ENV_NAME]-[BROKER_ID]
    broker_id: "[BROKER_ID]"
spec:
  replicas: 1
  selector:
    name: kafka-[ENV_NAME]-[BROKER_ID]
    broker_id: "[BROKER_ID]"
  template:
    metadata:
      labels:
        name: kafka-[ENV_NAME]-[BROKER_ID]
        broker_id: "[BROKER_ID]"
        service: kafka-[ENV_NAME]
    spec:
      nodeSelector:
        # run the label command to prepare
        # kubectl label node <SOME NODE> brokerNode=kafka-[ENV_NAME]-[BROKER_ID]
        brokerNode: kafka-[ENV_NAME]-[BROKER_ID]
      containers:
        - name: kafka
          securityContext:
            privileged: true
          image: navicore/kafka
          resources:
            requests:
              cpu: "200m"
              memory: "1500Mi"
          env:
            - name: NEW_RELIC_ENABLED
              value: "true"
            - name: JMX_PORT
              value: "9999"
            - name: KAFKA_HEAP_OPTS
              value: "-Xmx512M -Xms512M"
            - name: BROKER_ID
              value: "[BROKER_ID]"
            - name: NUM_PARTITIONS
              value: "4"
            - name: ADVERTISED_HOSTNAME
              value: "kafka-[ENV_NAME]-[BROKER_ID]"
            - name: ZOOKEEPER_CONNECT
              value: "[ZOO_PREF]1:2181,[ZOO_PREF]2:2181,[ZOO_PREF]3:2181"
            - name: RETENTION_HOURS
              value: "24"
          ports:
            - containerPort: 9092
              name: broker
            - containerPort: 9999
              name: jmx
          volumeMounts:
            - mountPath: /data
              name: data
      volumes:
        - name: data
          hostPath:
            # directory location on host
            path: /mnt/kafka-[ENV_NAME]-[BROKER_ID]/data

